r"""notebook.py -- append-only lab notebook for multi-session, multi-track investigations.

RIGOR skill: /lab-notebook. Stdlib-only, Python 3.10+.

State lives in a per-investigation directory (Layer-2 config: `notebook_dir` in
_shared/project_profile.yaml; pass it as --dir):

    <notebook_dir>/tracks.json      track registry (id, title, status, depends_on)
    <notebook_dir>/entries.jsonl    append-only log; one JSON object per line
    <notebook_dir>/NOTEBOOK.md      compiled report (regenerated by `compile`)

Entries are never edited or deleted -- corrections are new entries of type
`correction`. That is the integrity model: the notebook is evidence, not a wiki.

Commands:
    init      --dir D [--name "slug"] [--plan path/to/plan.md]
    track-add --dir D ID "title" [--depends A,B] [--status pending]
    track-set --dir D ID --status pending|active|blocked|done|dropped [--note "..."]
    log       --dir D ID --type progress|finding|blocker|decision|correction|next
                         --text "..." [--evidence p1,p2] [--refs 12,14]
    status    --dir D                 compact session-start digest (read this first)
    compile   --dir D [--out path]    full report -> NOTEBOOK.md
    check-narrative --dir D PATH      verify an agent-written narrative's #N citations
                                      against entries.jsonl (exit 1 on unknown ids)
"""
import argparse
import json
import re
import sys
import time
from pathlib import Path

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

STATUSES = ("pending", "active", "blocked", "done", "dropped")
TYPES = ("progress", "finding", "blocker", "decision", "correction", "next", "status")
TYPE_TAG = {"progress": "[prog]", "finding": "[FIND]", "blocker": "[BLKR]",
            "decision": "[decn]", "correction": "[corr]", "next": "[next]",
            "status": "[stat]"}


def utcnow():
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())


def today():
    return time.strftime("%Y-%m-%d")


class Notebook:
    def __init__(self, d):
        self.dir = Path(d)
        self.tracks_p = self.dir / "tracks.json"
        self.entries_p = self.dir / "entries.jsonl"

    def exists(self):
        return self.tracks_p.exists()

    def require(self):
        if not self.exists():
            sys.exit(f"[lab-notebook] no notebook at {self.dir} -- run `init` first")

    # ---- tracks ----
    def load_meta(self):
        return json.load(open(self.tracks_p, encoding="utf-8"))

    def save_meta(self, meta):
        self.tracks_p.write_text(json.dumps(meta, indent=1, ensure_ascii=False),
                                 encoding="utf-8")

    def track(self, meta, tid):
        for t in meta["tracks"]:
            if t["id"] == tid:
                return t
        sys.exit(f"[lab-notebook] unknown track '{tid}' "
                 f"(have: {', '.join(t['id'] for t in meta['tracks'])})")

    # ---- entries ----
    def load_entries(self):
        out = []
        if self.entries_p.exists():
            for line in open(self.entries_p, encoding="utf-8"):
                line = line.strip()
                if line:
                    out.append(json.loads(line))
        return out

    def append_entry(self, track, etype, text, evidence=None, refs=None):
        entries = self.load_entries()
        e = {"id": (entries[-1]["id"] + 1) if entries else 1,
             "ts": utcnow(), "session": today(),
             "track": track, "type": etype, "text": text}
        if evidence:
            e["evidence"] = evidence
        if refs:
            e["refs"] = refs
        with open(self.entries_p, "a", encoding="utf-8") as f:
            f.write(json.dumps(e, ensure_ascii=False) + "\n")
        return e


# ---------------- commands ----------------

def cmd_init(nb, args):
    if nb.exists():
        sys.exit(f"[lab-notebook] {nb.tracks_p} already exists -- refusing to overwrite")
    nb.dir.mkdir(parents=True, exist_ok=True)
    meta = {"investigation": args.name or nb.dir.name,
            "plan": args.plan or "", "created": utcnow(), "tracks": []}
    nb.save_meta(meta)
    nb.entries_p.touch()
    print(f"[ok] notebook initialised at {nb.dir}  (investigation: {meta['investigation']})")


def cmd_track_add(nb, args):
    nb.require()
    meta = nb.load_meta()
    if any(t["id"] == args.id for t in meta["tracks"]):
        sys.exit(f"[lab-notebook] track '{args.id}' already exists")
    if args.status not in STATUSES:
        sys.exit(f"[lab-notebook] status must be one of {STATUSES}")
    deps = [d.strip() for d in (args.depends or "").split(",") if d.strip()]
    known = {t["id"] for t in meta["tracks"]}
    for d in deps:
        if d not in known:
            print(f"[warn] dependency '{d}' is not (yet) a known track")
    meta["tracks"].append({"id": args.id, "title": args.title,
                           "status": args.status, "depends_on": deps})
    nb.save_meta(meta)
    print(f"[ok] track {args.id}: {args.title}  (status={args.status}"
          + (f", depends on {','.join(deps)}" if deps else "") + ")")


def cmd_track_set(nb, args):
    nb.require()
    meta = nb.load_meta()
    t = nb.track(meta, args.id)
    if args.status not in STATUSES:
        sys.exit(f"[lab-notebook] status must be one of {STATUSES}")
    old = t["status"]
    t["status"] = args.status
    nb.save_meta(meta)
    note = f"status {old} -> {args.status}" + (f": {args.note}" if args.note else "")
    nb.append_entry(args.id, "status", note)
    # blocked/dropped must carry their why as a first-class blocker/decision entry,
    # or the status digest (which scans those types) reports "(no ... entry logged)"
    why_type = {"blocked": "blocker", "dropped": "decision"}.get(args.status)
    if why_type and args.note:
        nb.append_entry(args.id, why_type, args.note)
    elif why_type:
        print(f"[warn] '{args.status}' without --note: log a `{why_type}` entry saying "
              f"why, or the status digest cannot show the reason")
    print(f"[ok] {args.id}: {note}")


def cmd_log(nb, args):
    nb.require()
    meta = nb.load_meta()
    nb.track(meta, args.id)  # validates the track id
    if args.type not in TYPES or args.type == "status":
        sys.exit(f"[lab-notebook] --type must be one of "
                 f"{[t for t in TYPES if t != 'status']}")
    evidence = [p.strip() for p in (args.evidence or "").split(",") if p.strip()]
    refs = [int(r) for r in (args.refs or "").split(",") if r.strip()]
    if args.type == "finding" and not evidence:
        print("[warn] a FINDING without --evidence is an assertion, not a result -- "
              "attach the artifact (CSV/figure/log) that shows it")
    if args.type == "correction" and not refs:
        print("[warn] a CORRECTION should point at the entry it supersedes "
              "(--refs <id>) -- without it, compile cannot mark the old entry")
    if refs:
        known_ids = {en["id"] for en in nb.load_entries()}
        for r in refs:
            if r not in known_ids:
                print(f"[warn] --refs {r}: no such entry id")
    root = Path(args.project_root or ".")
    for p in evidence:
        if not (root / p).exists() and not Path(p).exists():
            print(f"[warn] evidence path does not exist: {p}")
    e = nb.append_entry(args.id, args.type, args.text, evidence, refs)
    print(f"[ok] entry #{e['id']} {TYPE_TAG[args.type]} {args.id}: {args.text[:70]}")


def _latest_by_track(entries, etype=None):
    out = {}
    for e in entries:
        if etype is None or e["type"] == etype:
            out[e["track"]] = e
    return out


def cmd_status(nb, args):
    nb.require()
    meta = nb.load_meta()
    entries = nb.load_entries()
    last = _latest_by_track(entries)
    last_next = _latest_by_track(entries, "next")
    last_blkr = _latest_by_track(entries, "blocker")
    n_sessions = len({e["session"] for e in entries})
    print(f"== lab-notebook: {meta['investigation']} -- "
          f"{len(meta['tracks'])} tracks, {len(entries)} entries, "
          f"{n_sessions} session(s)"
          + (f", plan: {meta['plan']}" if meta.get("plan") else "") + " ==")
    order = {"active": 0, "blocked": 1, "pending": 2, "done": 3, "dropped": 4}
    for t in sorted(meta["tracks"], key=lambda t: (order.get(t["status"], 9), t["id"])):
        le = last.get(t["id"])
        tail = (f"  last {le['session']} {TYPE_TAG.get(le['type'], '[????]')} "
                f"{le['text'][:60]}" if le else "  (no entries)")
        deps = f"  <deps: {','.join(t['depends_on'])}>" if t["depends_on"] else ""
        print(f"{t['status'].upper():8s} {t['id']:9s} {t['title'][:44]:44s}{deps}{tail}")
    blocked = [t for t in meta["tracks"] if t["status"] == "blocked"]
    if blocked:
        print("-- open blockers --")
        for t in blocked:
            b = last_blkr.get(t["id"])
            print(f"  {t['id']}: {b['text'] if b else '(no blocker entry logged)'}")
    tmap = {t["id"]: t for t in meta["tracks"]}
    nxt = [(tid, e) for tid, e in last_next.items()
           if tmap.get(tid, {}).get("status") not in ("done", "dropped")]
    if nxt:
        print("-- queued next-steps --")
        for tid, e in sorted(nxt):
            stale = (" (stale? later entries exist)"
                     if last.get(tid, e)["id"] != e["id"] else "")
            print(f"  {tid}: {e['text'][:90]}{stale}")


def cmd_compile(nb, args):
    nb.require()
    meta = nb.load_meta()
    entries = nb.load_entries()
    by_track = {}
    for e in entries:
        by_track.setdefault(e["track"], []).append(e)
    superseded = {}  # entry id -> ids of the corrections that point at it
    for e in entries:
        if e["type"] == "correction":
            for r in e.get("refs", []):
                superseded.setdefault(r, []).append(e["id"])
    L = [f"# Lab notebook -- {meta['investigation']}", "",
         f"*Compiled {utcnow()} from {len(entries)} append-only entries across "
         f"{len({e['session'] for e in entries})} session(s). "
         f"Source of truth: `entries.jsonl` (never edited). "
         + (f"Investigation plan: `{meta['plan']}`.*" if meta.get("plan") else "*"), "",
         "## Track summary", "",
         "| track | title | status | depends on | entries | last update |",
         "|---|---|---|---|---|---|"]
    for t in meta["tracks"]:
        es = by_track.get(t["id"], [])
        L.append(f"| {t['id']} | {t['title']} | **{t['status']}** | "
                 f"{', '.join(t['depends_on']) or '--'} | {len(es)} | "
                 f"{es[-1]['session'] if es else '--'} |")
    L += ["", "## Per-track chronology", ""]
    for t in meta["tracks"]:
        es = by_track.get(t["id"], [])
        L.append(f"### {t['id']} -- {t['title']}  (status: {t['status']})")
        if not es:
            L += ["", "*(no entries yet)*", ""]
            continue
        L.append("")
        for e in es:
            ev = ("  \n  evidence: " + ", ".join(f"`{p}`" for p in e["evidence"])
                  if e.get("evidence") else "")
            rf = (f" (re: #{', #'.join(map(str, e['refs']))})" if e.get("refs") else "")
            sup = (" **[superseded by #" + ", #".join(map(str, superseded[e["id"]])) + "]**"
                   if e["id"] in superseded else "")
            L.append(f"- **#{e['id']}** {e['session']} {TYPE_TAG.get(e['type'], '[????]')} "
                     f"{e['text']}{sup}{rf}{ev}")
        L.append("")
    L += ["## Session index", ""]
    by_sess = {}
    for e in entries:
        by_sess.setdefault(e["session"], []).append(e)
    for s in sorted(by_sess):
        es = by_sess[s]
        tracks = sorted({e["track"] for e in es})
        L.append(f"- **{s}** -- {len(es)} entries across {', '.join(tracks)}")
    out = Path(args.out) if args.out else nb.dir / "NOTEBOOK.md"
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"[ok] compiled -> {out}  ({len(entries)} entries, {len(meta['tracks'])} tracks)")


def cmd_check_narrative(nb, args):
    """Mechanical guardrail for the sub-agent-written narrative: every entry citation
    (#N) must exist in entries.jsonl; citing a superseded entry draws a warning;
    findings the narrative never used are listed. Report-only -- never edits."""
    nb.require()
    entries = nb.load_entries()
    known = {e["id"]: e for e in entries}
    superseded = {}
    for e in entries:
        if e["type"] == "correction":
            for r in e.get("refs", []):
                superseded.setdefault(r, []).append(e["id"])
    text = Path(args.narrative).read_text(encoding="utf-8")
    cited = {int(m) for m in re.findall(r"#(\d+)\b", text)}
    bad = sorted(c for c in cited if c not in known)
    stale = sorted(c for c in cited if c in superseded)
    print(f"[check-narrative] {args.narrative}: {len(cited)} distinct entry "
          f"citation(s) over {len(known)} log entries")
    for c in bad:
        print(f"  [FAIL] cites #{c} -- no such entry in entries.jsonl")
    for c in stale:
        print(f"  [warn] cites #{c}, superseded by "
              f"#{', #'.join(map(str, superseded[c]))} -- quote the correction instead")
    uncited = [e for e in entries if e["type"] == "finding"
               and e["id"] not in cited and e["id"] not in superseded]
    if uncited:
        print(f"  [info] {len(uncited)} finding(s) the narrative never cites: "
              + ", ".join(f"#{e['id']}" for e in uncited))
    if not cited:
        print("  [FAIL] the narrative cites no entries at all -- it cannot be grounded")
    if bad or not cited:
        sys.exit(1)
    print("  [ok] every citation resolves to a real entry")


def main():
    ap = argparse.ArgumentParser(description="append-only lab notebook (RIGOR)")
    ap.add_argument("--dir", required=True, help="notebook directory (Layer-2: "
                    "`notebook_dir` in _shared/project_profile.yaml)")
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("init")
    p.add_argument("--name", help="investigation slug (default: dir name)")
    p.add_argument("--plan", help="path to the investigation plan document")

    p = sub.add_parser("track-add")
    p.add_argument("id"); p.add_argument("title")
    p.add_argument("--depends", help="comma-separated track ids")
    p.add_argument("--status", default="pending")

    p = sub.add_parser("track-set")
    p.add_argument("id"); p.add_argument("--status", required=True)
    p.add_argument("--note", help="why (logged as a status entry)")

    p = sub.add_parser("log")
    p.add_argument("id"); p.add_argument("--type", required=True)
    p.add_argument("--text", required=True)
    p.add_argument("--evidence", help="comma-separated artifact paths")
    p.add_argument("--refs", help="comma-separated entry ids this corrects/extends")
    p.add_argument("--project-root", help="root for resolving evidence paths")

    sub.add_parser("status")

    p = sub.add_parser("compile")
    p.add_argument("--out", help="output path (default: <dir>/NOTEBOOK.md)")

    p = sub.add_parser("check-narrative")
    p.add_argument("narrative", help="path to the agent-written narrative markdown")

    args = ap.parse_args()
    nb = Notebook(args.dir)
    {"init": cmd_init, "track-add": cmd_track_add, "track-set": cmd_track_set,
     "log": cmd_log, "status": cmd_status, "compile": cmd_compile,
     "check-narrative": cmd_check_narrative}[args.cmd](nb, args)


if __name__ == "__main__":
    main()
